/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import network.ClientSocket;

/**
 *
 * @author Admin
 */
public class FriendDialog extends javax.swing.JDialog {

    private String myEmail;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FriendDialog.class.getName());

    /**
     * Creates new form FriendDialog
     */
    public FriendDialog(JFrame parent, String email) {
        super(parent, true);
        this.myEmail = email;
        initComponents();
        loadUsers();
    }

    private void loadUsers() {
        String res = ClientSocket.getInstance()
                .sendRequest("GET_NOT_FRIEND_USERS;" + myEmail);

        if (!res.startsWith("USER_LIST")) {
            JOptionPane.showMessageDialog(this, "Không lấy được user");
            return;
        }

        DefaultListModel<String> model = new DefaultListModel<>();
        String[] arr = res.split(";");

        for (int i = 1; i < arr.length; i++) {
            model.addElement(arr[i]); // id:email
        }

        listUser.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listUser = new javax.swing.JList<>();
        btnClose = new javax.swing.JButton();
        btnAddFriend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        listUser.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listUser);

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnAddFriend.setText("Add Friend");
        btnAddFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFriendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btnAddFriend)
                        .addGap(70, 70, 70)
                        .addComponent(btnClose)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnAddFriend))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFriendActionPerformed
        // TODO add your handling code here:
        String selected = listUser.getSelectedValue();
        if (selected == null) {
            JOptionPane.showMessageDialog(this, "Chọn user trước");
            return;
        }

        String[] p = selected.split(":");
        int friendId = Integer.parseInt(p[0]);
        String email = p[1];

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Gửi lời mời kết bạn tới " + email + "?",
                "Add Friend",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        String res = ClientSocket.getInstance()
                .sendRequest("ADD_FRIEND;" + myEmail + ";" + friendId);

        if (res.equals("ADD_FRIEND_SUCCESS")) {
            JOptionPane.showMessageDialog(this, "Đã gửi lời mời!");
            loadUsers(); // refresh list
        } else {
            JOptionPane.showMessageDialog(this, "Thất bại");
        }
    }//GEN-LAST:event_btnAddFriendActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFriend;
    private javax.swing.JButton btnClose;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listUser;
    // End of variables declaration//GEN-END:variables
}
