/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package view;

import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import network.ClientSocket;

/**
 *
 * @author Admin
 */
public class JoinGroupDialog extends JDialog {

    private String myEmail;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JoinGroupDialog.class.getName());

    /**
     * Creates new form JoinGroupDialog
     */
    public JoinGroupDialog(JFrame parent, String email) {
        super(parent, true); // modal dialog
        this.myEmail = email; // 🔥 BẮT BUỘC
        initComponents();
        setLocationRelativeTo(parent);
        loadNotJoinedGroups(); // 🔥 gọi load
    }

    private void loadNotJoinedGroups() {
        String res = ClientSocket.getInstance()
                .sendRequest("GET_NOT_JOINED_GROUPS;" + myEmail);

        if (!res.startsWith("GROUP_LIST")) {
            JOptionPane.showMessageDialog(this, "Không lấy được danh sách group");
            return;
        }

        String[] arr = res.split(";");
        DefaultListModel<String> model = new DefaultListModel<>();

        for (int i = 1; i < arr.length; i++) {
            model.addElement(arr[i]); // id:name
        }

        listGroup.setModel(model);

    }

    private void joinSelectedGroup() {
        String selected = listGroup.getSelectedValue();
        if (selected == null) {
            JOptionPane.showMessageDialog(this, "Chọn group trước");
            return;
        }

        String[] parts = selected.split(":");
        int groupId = Integer.parseInt(parts[0]);
        String groupName = parts[1];

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Tham gia group \"" + groupName + "\" ?",
                "Join Group",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        String res = ClientSocket.getInstance()
                .sendRequest("JOIN_GROUP;" + myEmail + ";" + groupId);

        if (res.equals("JOIN_GROUP_SUCCESS")) {
            JOptionPane.showMessageDialog(this, "Join thành công!");
            dispose(); // đóng dialog
        } else {
            JOptionPane.showMessageDialog(this, "Join thất bại");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listGroup = new javax.swing.JList<>();
        btnJoinGroup = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("List Group");

        listGroup.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listGroup);

        btnJoinGroup.setLabel("Join Group");
        btnJoinGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinGroupActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.setToolTipText("");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnJoinGroup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJoinGroup)
                    .addComponent(btnClose))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        btnJoinGroup.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJoinGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinGroupActionPerformed
        // TODO add your handling code here:
        joinSelectedGroup();
    }//GEN-LAST:event_btnJoinGroupActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnJoinGroup;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listGroup;
    // End of variables declaration//GEN-END:variables

}
