/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import network.ClientSocket;

/**
 *
 * @author Admin
 */
public class ViewProfileFriend extends javax.swing.JDialog {
    private int friendId;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewProfileFriend.class.getName());

    /**
     * Creates new form ViewProfileFriend
     */
   public ViewProfileFriend(java.awt.Frame parent, boolean modal, int friendId) {
    super(parent, modal);
    this.friendId = friendId;
    initComponents();
    loadProfile();
}
   
private void loadProfile() {
    String res = ClientSocket.getInstance()
            .sendRequest("GET_USER_PROFILE;" + friendId);

    System.out.println("PROFILE RESPONSE = " + res);

    if (res == null || !res.startsWith("USER_PROFILE;")) {
        JOptionPane.showMessageDialog(
            this,
            "Không lấy được thông tin người dùng",
            "Lỗi",
            JOptionPane.ERROR_MESSAGE
        );
        dispose();
        return;
    }

    String[] p = res.split(";");
    if (p.length < 4) {
        JOptionPane.showMessageDialog(this, "Dữ liệu profile không hợp lệ");
        dispose();
        return;
    }

    txtName.setText(p[1]);
    txtGender.setText(p[2]);
    txtDOB.setText(p[3]);

    txtName.setEditable(false);
    txtGender.setEditable(false);
    txtDOB.setEditable(false);
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Full Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 94, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Gender");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 94, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Date Of Birth");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 111, -1));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 230, -1));
        getContentPane().add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 230, -1));
        getContentPane().add(txtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 230, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("View Profile");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        setBounds(0, 0, 414, 308);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
